version: "3.7"
services:
    db:
        #build:
        #    context: .
        #    dockerfile: Dockerfile
        image: mariadb:10.4
        container_name: maria_mall
        environment:
            MARIADB_ROOT_PASSWORD: totallysecurepassword
        volumes:
            - ./mdbdata:/var/lib/mysql
            - ./volumes:/volumes
        networks:
            net-172.19.52.0:
                ipv4_address: 172.19.52.2
    pmp:
        container_name: phpmyadmin_mall
        image: phpmyadmin/phpmyadmin:latest
        ports: 
        - '8082:80'
        networks:
            net-172.19.52.0:
                ipv4_address: 172.19.52.3

    py:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: python_mall
        tty:
            true
        dns:
            - '8.8.8.8'
        networks:
            net-172.19.52.0:
                ipv4_address: 172.19.52.4
        volumes: 
            - ./volumes:/volumes

        

networks:
    net-172.19.52.0:
        name: net-172.19.52.0
        ipam:
            config:
                - subnet: 172.19.52.0/24
