

-- 23 tables

-- Independent: Customer, Zone_manager, Vehicle, Transactions, Importer

-- Single: Mobile Numbers (Manager, Store, Sec, Maintenance, Customer, Importer), Importer Visits, Utility Room

-- Double: Parking, Transaction List, Store, Employees(Store, Maintenance, Sec), Maintenance Performed, Store Item, Restock Trans

-- Triple: Bought By






CREATE TABLE CUSTOMER (
	SSN CHAR(12) PRIMARY KEY,
	NAME VARCHAR(50) NOT NULL
);

CREATE TABLE ZONE_MANAGER(
	ID CHAR(12) NOT NULL UNIQUE,
	NAME VARCHAR(50) NOT NULL,
	DOB DATE,
	ADDRESS VARCHAR(100),
	SALARY INT NOT NULL,
	SEX CHAR(1),
	AGE INT,
	ZONE INT PRIMARY KEY,
	ZONE_NAME VARCHAR(50) NOT NULL
);


CREATE TABLE TRANS (
	T_ID VARCHAR(100) PRIMARY KEY,
	T_TIME DATE NOT NULL,
	AMOUNT INT
);

CREATE TABLE IMPORTER (
	SSN CHAR(12) PRIMARY KEY,
	NAME VARCHAR(50) NOT NULL
);

CREATE TABLE CUSTOMER_MOBILE(
	SSN CHAR(12),
	NUM VARCHAR(14),
	PRIMARY KEY (SSN, NUM),
	FOREIGN KEY (SSN) REFERENCES CUSTOMER(SSN)
);


CREATE TABLE IMPORTER_MOBILE(
	SSN CHAR(12),
	NUM VARCHAR(14),
	PRIMARY KEY (SSN, NUM),
	FOREIGN KEY (SSN) REFERENCES IMPORTER(SSN)
);

CREATE TABLE MANAGER_MOBILE(
	SSN CHAR(12),
	NUM VARCHAR(14),
	PRIMARY KEY (SSN, NUM),
	FOREIGN KEY (SSN) REFERENCES ZONE_MANAGER(ID)
);



-- CIRCULAR REFERENCE WITH STORE AND STORE EMPLOYEE. 
-- CREATE NOW, ALTER LATER 
CREATE TABLE STORE (
	STORE_ID VARCHAR(5) PRIMARY KEY,
	STORE_NAME VARCHAR(50) NOT NULL,
	SUPER_ID CHAR(12),	-- SUPPOSED TO BE A FOREIGN KEY
	ZONE INT,
	FOREIGN KEY (ZONE) REFERENCES ZONE_MANAGER(ZONE)
);

CREATE TABLE STORE_EMPLOYEE(
	ID CHAR(12) PRIMARY KEY,
	NAME VARCHAR(50) NOT NULL,
	DOB DATE,
	ADDRESS VARCHAR(100),
	SALARY INT NOT NULL,
	SEX CHAR(1),
	AGE INT,
	STORE_ID VARCHAR(5) NOT NULL,
	SUPER_ID CHAR(12),
	FOREIGN KEY (STORE_ID) REFERENCES STORE(STORE_ID)
);

ALTER TABLE STORE_EMPLOYEE ADD FOREIGN KEY (SUPER_ID) REFERENCES STORE_EMPLOYEE(ID);

ALTER TABLE STORE ADD FOREIGN KEY (SUPER_ID) REFERENCES STORE_EMPLOYEE(ID);

CREATE TABLE RESTOCK_TRANS(
	ID VARCHAR(100) PRIMARY KEY,
	IMPORTER_ID CHAR(12) NOT NULL,
	EMPLOYEE_ID CHAR(12) NOT NULL,
	TIME_OF_RESTOCK DATE NOT NULL,
	FOREIGN KEY (IMPORTER_ID) REFERENCES IMPORTER(SSN),
	FOREIGN KEY (EMPLOYEE_ID) REFERENCES STORE_EMPLOYEE(ID)
);

CREATE TABLE STORE_ITEM (
	ID VARCHAR(12) PRIMARY KEY,
	ITEM_NAME VARCHAR(40),
	ITEM_CLASS VARCHAR(40) NOT NULL,
	TAX FLOAT NOT NULL,
	AMOUNT FLOAT NOT NULL,
	QUANTITY INT,
	STORE_ID VARCHAR(5) NOT NULL,
	FOREIGN KEY (STORE_ID) REFERENCES STORE(STORE_ID)
);
ALTER TABLE STORE_ITEM ALTER TAX SET DEFAULT 0;

CREATE TABLE STORE_MOBILE(
	ID CHAR(12),
	NUM VARCHAR(14),
	PRIMARY KEY (ID, NUM),
	FOREIGN KEY (ID) REFERENCES STORE_EMPLOYEE(ID)
);

CREATE TABLE TRANSACTION_LIST(
	T_ID VARCHAR(100) NOT NULL,
	ITEM_ID VARCHAR(12) NOT NULL,
	QTY INT NOT NULL,
	PRIMARY KEY (T_ID, ITEM_ID),
	FOREIGN KEY (T_ID) REFERENCES TRANS(T_ID),
	FOREIGN KEY (ITEM_ID) REFERENCES STORE_ITEM(ID)	
);

CREATE TABLE BOUGHT_BY(
	SSN CHAR(12) NOT NULL,
	T_ID VARCHAR(100) NOT NULL,
	EMP_ID CHAR(12) NOT NULL,
	PRIMARY KEY (SSN, T_ID, EMP_ID),
	FOREIGN KEY (SSN) REFERENCES CUSTOMER(SSN),
	FOREIGN KEY (T_ID) REFERENCES TRANS(T_ID),
	FOREIGN KEY (EMP_ID) REFERENCES STORE_EMPLOYEE(ID)
);



















